using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BehineNiroo.Models
{
    public class Log
    {
        public DateTime LogTime { get; set; }
        public double FreqMin { get; set; }
        public double Freq { get; set; }
        public double FreqMax { get; set; }
        public double V1min { get; set; }
        public double V1 { get; set; }
        public double V1Max { get; set; }
        public double I1min { get; set; }
        public double I1 { get; set; }
        public double I1max { get; set; }
        public double P1min { get; set; }
        public double P1 { get; set; }
        public double P1max { get; set; }
        public double ExportEnergymin { get; set; }
        public double ExportEnergy { get; set; }
        public double ExportEnergymax { get; set; }
        public double ImportEnergymin { get; set; }
        public double ImportEnergy { get; set; }
        public double ImportEnergymax { get; set; }
        public double V12min { get; set; }
        public double V12 { get; set; }
        public double V12max { get; set; }
        public double V2min { get; set; }
        public double V2 { get; set; }
        public double V2max { get; set; }
        public double I2min { get; set; }
        public double I2 { get; set; }
        public double I2max { get; set; }
        public double P2min { get; set; }
        public double P2 { get; set; }
        public double P2max { get; set; }
        public double V23min { get; set; }
        public double V23 { get; set; }
        public double V23max { get; set; }
        public double V3min { get; set; }
        public double V3 { get; set; }
        public double V3max { get; set; }
        public double I3min { get; set; }
        public double I3 { get; set; }
        public double I3max { get; set; }
        public double P3min { get; set; }
        public double P3 { get; set; }
        public double P3max { get; set; }
        public double V31min { get; set; }
        public double V31 { get; set; }
        public double V31max { get; set; }
        public double Ptotmin { get; set; }
        public double Ptot { get; set; }
        public double Ptotmax { get; set; }
        public double Innmin { get; set; }
        public double Inn { get; set; }
        public double Innmax { get; set; }
        public double Qtotmin { get; set; }
        public double Qtot { get; set; }
        public double Qtotmax { get; set; }
        public double DigitalInputmin { get; set; }
        public double DigitalInput { get; set; }
        public double DigitalInputmax { get; set; }
        public double Stopmin { get; set; }
        public double Stop{ get; set; }
        public double Stopmax { get; set; }
        public double S1min { get; set; }
        public double S1 { get; set; }
        public double S1max { get; set; }
        public double Q1min { get; set; }
        public double Q1 { get; set; }
        public double Q1max { get; set; }
        public double S2min { get; set; }
        public double S2 { get; set; }
        public double S2max { get; set; }
        public double Q2min { get; set; }
        public double Q2 { get; set; }
        public double Q2max { get; set; }
        public double S3min { get; set; }
        public double S3 { get; set; }
        public double S3max { get; set; }
        public double Q3min { get; set; }
        public double Q3 { get; set; }
        public double Q3max { get; set; }
        public double PF1min { get; set; }
        public double PF1 { get; set; }
        public double PF1max { get; set; }
        public double PF2min { get; set; }
        public double PF2 { get; set; }
        public double PF2max { get; set; }
        public double PF3min { get; set; }
        public double PF3 { get; set; }
        public double PF3max { get; set; }
        public double PFtotmin { get; set; }
        public double PFtot { get; set; }
        public double PFtotmax { get; set; }
        public double THDV1min { get; set; }
        public double THDV1 { get; set; }
        public double THDV1max { get; set; }
        public double Harm3V1min { get; set; }
        public double Harm3V1 { get; set; }
        public double Harm3V1max { get; set; }
        public double Harm5V1min { get; set; }
        public double Harm5V1 { get; set; }
        public double Harm5V1max { get; set; }
        public double Harm7V1min { get; set; }
        public double Harm7V1 { get; set; }
        public double Harm7V1max { get; set; }
        public double Harm9V1min { get; set; }
        public double Harm9V1 { get; set; }
        public double Harm9V1max { get; set; }
        public double THDI1min { get; set; }
        public double THDI1 { get; set; }
        public double THDI1max { get; set; }
        public double Harm3I1min { get; set; }
        public double Harm3I1 { get; set; }
        public double Harm3I1max { get; set; }
        public double Harm5I1min { get; set; }
        public double Harm5I1 { get; set; }
        public double Harm5I1max { get; set; }
        public double Harm7I1min { get; set; }
        public double Harm7I1 { get; set; }
        public double Harm7I1max { get; set; }
        public double Harm9I1min { get; set; }
        public double Harm9I1 { get; set; }
        public double Harm9I1max { get; set; }
        public double THDV2min { get; set; }
        public double THDV2 { get; set; }
        public double THDV2max { get; set; }
        public double Harm3V2min { get; set; }
        public double Harm3V2 { get; set; }
        public double Harm3V2max { get; set; }
        public double Harm5V2min { get; set; }
        public double Harm5V2 { get; set; }
        public double Harm5V2max { get; set; }
        public double Harm7V2min { get; set; }
        public double Harm7V2 { get; set; }
        public double Harm7V2max { get; set; }
        public double Harm9V2min { get; set; }
        public double Harm9V2 { get; set; }
        public double Harm9V2max { get; set; }
        public double THDI2min { get; set; }
        public double THDI2 { get; set; }
        public double THDI2max { get; set; }
        public double Harm3I2min { get; set; }
        public double Harm3I2 { get; set; }
        public double Harm3I2max { get; set; }
        public double Harm5I2min { get; set; }
        public double Harm5I2 { get; set; }
        public double Harm5I2max { get; set; }
        public double Harm7I2min { get; set; }
        public double Harm7I2 { get; set; }
        public double Harm7I2max { get; set; }
        public double Harm9I2min { get; set; }
        public double Harm9I2 { get; set; }
        public double Harm9I2max { get; set; }
        public double THDV3min { get; set; }
        public double THDV3 { get; set; }
        public double THDV3max { get; set; }
        public double Harm3V3min { get; set; }
        public double Harm3V3 { get; set; }
        public double Harm3V3max { get; set; }
        public double Harm5V3min { get; set; }
        public double Harm5V3 { get; set; }
        public double Harm5V3max { get; set; }
        public double Harm7V3min { get; set; }
        public double Harm7V3 { get; set; }
        public double Harm7V3max { get; set; }
        public double Harm9V3min { get; set; }
        public double Harm9V3 { get; set; }
        public double Harm9V3max { get; set; }
        public double THDI3min { get; set; }
        public double THDI3 { get; set; }
        public double THDI3max { get; set; }
        public double Harm3I3min { get; set; }
        public double Harm3I3 { get; set; }
        public double Harm3I3max { get; set; }
        public double Harm5I3min { get; set; }
        public double Harm5I3 { get; set; }
        public double Harm5I3max { get; set; }
        public double Harm7I3min { get; set; }
        public double Harm7I3 { get; set; }
        public double Harm7I3max { get; set; }
        public double Harm9I3min { get; set; }
        public double Harm9I3 { get; set; }
        public double Harm9I3max { get; set; }
        public double VUnBalancemin { get; set; }
        public double VUnBalance { get; set; }
        public double VUnBalancemax { get; set; }
    }
}
